name: CI
on:
  push:
    branches: M32-KSU-Next
    paths:
      - '.github/workflows/main.yml'
      - 'action.yml'

  pull_request:

jobs:
  ci-test:
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/Samo141988/android_kernel_samsung_m32
          
          kernel-branch: Thirteen-Ksu-Next
          config: rsuntk_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          ksu: true
          ksu-version: next
          android-version: 12
          
          
          anykernel3: true
